# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Configuration for Python pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "pip dependencies"
    #versioning-strategy: lockfile-only
    #allow:
      # Allow both direct and indirect updates for all packages
    #  - dependency-type: "all"
    #reviewers:
    #  - "team-python"         # Optional: Specify reviewers for pull requests.